<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_product extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_product_model');
    } 

    /*
     * Listing of company_product
     */
    function index()
    {
        $data['company_product'] = $this->Company_product_model->get_all_company_product();
        
        $data['_view'] = 'company_product/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new company_product
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('description','Description','required|max_length[1500]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'description' => $this->input->post('description'),
            );
            
            $company_product_id = $this->Company_product_model->add_company_product($params);
            redirect('company_product/index');
        }
        else
        {            
            $data['_view'] = 'company_product/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a company_product
     */
    function edit($company_product_id)
    {   
        // check if the company_product exists before trying to edit it
        $data['company_product'] = $this->Company_product_model->get_company_product($company_product_id);
        
        if(isset($data['company_product']['company_product_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('description','Description','required|max_length[1500]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'description' => $this->input->post('description'),
                );

                $this->Company_product_model->update_company_product($company_product_id,$params);            
                redirect('company_product/index');
            }
            else
            {
                $data['_view'] = 'company_product/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The company_product you are trying to edit does not exist.');
    } 

    /*
     * Deleting company_product
     */
    function remove($company_product_id)
    {
        $company_product = $this->Company_product_model->get_company_product($company_product_id);

        // check if the company_product exists before trying to delete it
        if(isset($company_product['company_product_id']))
        {
            $this->Company_product_model->delete_company_product($company_product_id);
            redirect('company_product/index');
        }
        else
            show_error('The company_product you are trying to delete does not exist.');
    }
    
}
