<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_contact_person extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_contact_person_model');
    } 

    /*
     * Listing of company_contact_person
     */
    function index()
    {
        $data['company_contact_person'] = $this->Company_contact_person_model->get_all_company_contact_person();
        
        $data['_view'] = 'company_contact_person/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new company_contact_person
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $company_contact_person_id = $this->Company_contact_person_model->add_company_contact_person($params);
            redirect('company_contact_person/index');
        }
        else
        {            
            $data['_view'] = 'company_contact_person/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a company_contact_person
     */
    function edit($company_id)
    {   
        // check if the company_contact_person exists before trying to edit it
        $data['company_contact_person'] = $this->Company_contact_person_model->get_company_contact_person($company_id);
        
        if(isset($data['company_contact_person']['company_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Company_contact_person_model->update_company_contact_person($company_id,$params);            
                redirect('company_contact_person/index');
            }
            else
            {
                $data['_view'] = 'company_contact_person/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The company_contact_person you are trying to edit does not exist.');
    } 

    /*
     * Deleting company_contact_person
     */
    function remove($company_id)
    {
        $company_contact_person = $this->Company_contact_person_model->get_company_contact_person($company_id);

        // check if the company_contact_person exists before trying to delete it
        if(isset($company_contact_person['company_id']))
        {
            $this->Company_contact_person_model->delete_company_contact_person($company_id);
            redirect('company_contact_person/index');
        }
        else
            show_error('The company_contact_person you are trying to delete does not exist.');
    }
    
}
