<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dashboard_model');
    }

    function index()
    {
       

        $data['company'] = $this->Dashboard_model->get_all_company();
        
        $data['_view'] = 'dashboard/index';
        $this->load->view('layouts/main',$data);
    }


}

