<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Expertise extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Expertise_model');
    } 

    /*
     * Listing of expertise
     */
    function index()
    {
        $data['expertise'] = $this->Expertise_model->get_all_expertise();
        
        $data['_view'] = 'expertise/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new expertise
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('expertise_area','Expertise Area','required|max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'expertise_area' => $this->input->post('expertise_area'),
            );
            
            $expertise_id = $this->Expertise_model->add_expertise($params);
            redirect('expertise/index');
        }
        else
        {            
            $data['_view'] = 'expertise/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a expertise
     */
    function edit($expertise_id)
    {   
        // check if the expertise exists before trying to edit it
        $data['expertise'] = $this->Expertise_model->get_expertise($expertise_id);
        
        if(isset($data['expertise']['expertise_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('expertise_area','Expertise Area','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'expertise_area' => $this->input->post('expertise_area'),
                );

                $this->Expertise_model->update_expertise($expertise_id,$params);            
                redirect('expertise/index');
            }
            else
            {
                $data['_view'] = 'expertise/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The expertise you are trying to edit does not exist.');
    } 

    /*
     * Deleting expertise
     */
    function remove($expertise_id)
    {
        $expertise = $this->Expertise_model->get_expertise($expertise_id);

        // check if the expertise exists before trying to delete it
        if(isset($expertise['expertise_id']))
        {
            $this->Expertise_model->delete_expertise($expertise_id);
            redirect('expertise/index');
        }
        else
            show_error('The expertise you are trying to delete does not exist.');
    }
    
}
