<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Home extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $this->load->view('home');
    }
    function logins(){
        $this->load->library('form_validation');

		$this->form_validation->set_rules('username','username','required');
		$this->form_validation->set_rules('password','password','required');
        if($this->form_validation->run())  {   
       
           
				$username = $this->input->post('username');
				$password = $this->input->post('password');
           
            
           
            // Always start this first
            session_start();
            
            if ( ! empty( $_POST ) ) {
                $_SESSION['login_user']=$username;
                if ( $_SESSION['login_user'] ==='adc') {
                   $data['_view'] = 'dashboard/dashboard';
        $this->load->view('layouts/main',$data);
        
                }
                elseif ($_SESSION['login_user'] ==='company'){
                    //company login code goes here
                    $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
                }
                else
                $this->load->view('home');
                }
            
           
        }
        else
        {            
          //  $data['_view'] = 'home';
            $this->load->view('home');
        }
    }
    }  

