<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programme extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Programme_model');
    } 

    /*
     * Listing of programmes
     */
    function index()
    {
        $data['programmes'] = $this->Programme_model->get_all_programmes();
        
        $data['_view'] = 'programme/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new programme
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('programme_type','Programme Type','required|max_length[100]');
		$this->form_validation->set_rules('description','Description','required|max_length[1500]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'programme_type' => $this->input->post('programme_type'),
				'description' => $this->input->post('description'),
            );
            
            $programme_id = $this->Programme_model->add_programme($params);
            redirect('programme/index');
        }
        else
        {            
            $data['_view'] = 'programme/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a programme
     */
    function edit($programme_id)
    {   
        // check if the programme exists before trying to edit it
        $data['programme'] = $this->Programme_model->get_programme($programme_id);
        
        if(isset($data['programme']['programme_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('programme_type','Programme Type','required|max_length[100]');
			$this->form_validation->set_rules('description','Description','required|max_length[1500]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'programme_type' => $this->input->post('programme_type'),
					'description' => $this->input->post('description'),
                );

                $this->Programme_model->update_programme($programme_id,$params);            
                redirect('programme/index');
            }
            else
            {
                $data['_view'] = 'programme/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The programme you are trying to edit does not exist.');
    } 

    /*
     * Deleting programme
     */
    function remove($programme_id)
    {
        $programme = $this->Programme_model->get_programme($programme_id);

        // check if the programme exists before trying to delete it
        if(isset($programme['programme_id']))
        {
            $this->Programme_model->delete_programme($programme_id);
            redirect('programme/index');
        }
        else
            show_error('The programme you are trying to delete does not exist.');
    }
    
}
