<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Business_registration_info_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get business_registration_info by bri_id
     */
    function get_business_registration_info($bri_id)
    {
        return $this->db->get_where('business_registration_info',array('bri_id'=>$bri_id))->row_array();
    }
        
    /*
     * Get all business_registration_info
     */
    function get_all_business_registration_info()
    {
        $this->db->order_by('bri_id', 'desc');
        return $this->db->get('business_registration_info')->result_array();
    }
        
    /*
     * function to add new business_registration_info
     */
    function add_business_registration_info($params)
    {
        $this->db->insert('business_registration_info',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update business_registration_info
     */
    function update_business_registration_info($bri_id,$params)
    {
        $this->db->where('bri_id',$bri_id);
        return $this->db->update('business_registration_info',$params);
    }
    
    /*
     * function to delete business_registration_info
     */
    function delete_business_registration_info($bri_id)
    {
        return $this->db->delete('business_registration_info',array('bri_id'=>$bri_id));
    }
}
