<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

   
    
    /*
     * Get company by id
     */
    function get_company($company_id)
    {
        return $this->db->get_where('company',array('company_id'=>$company_id))->row_array();
       // return $this->db->get_where('business_registration_info',array('bri_id'=>$bri_id))->row_array();
  
    }
        
    /*
     * Get all company
     */
    function get_all_company()
    {
       // $this->db->order_by('id', 'desc');
        return $this->db->get('company')->result_array();
        $this->db->order_by('bri_id', 'desc');
        return $this->db->get('business_registration_info')->result_array();
   
    }
        
    /*
     * function to add new company
     */

   
    function add_company($params)
    {
        
        
        //$fileName = $_FILES['path_of_file']['name'];
        
        $this->db->insert('company',array_slice($params,0,12));
        $this->db->insert('business_registration_info',array_slice($params, 12)); 
        return $this->db->insert_id();
    }  
        
   # $config = Array(
  #'protocol' => 'smtp',
  #'smtp_host' => 'ssl://smtp.googlemail.com',
  #'smtp_port' => 465,
  #'smtp_user' => 'mphrama545@gmail.com', // change it to yours
  #'smtp_pass' => '', // change it to yours
  #'mailtype' => 'html',
  #'charset' => 'iso-8859-1',
  #'wordwrap' => TRUE
#);

     #   $message = 'hi test msg';
    #    $this->load->library('email', $config);
    #  $this->email->set_newline("\r\n");
    #  $this->email->from('emmanuelkobinao11@gmail.com'); // change it to yours
     # $this->email->to('mphrama545@gmail.com');// change it to yours
     # $this->email->subject('Resume from JobsBuddy for your Job posting');
     # $this->email->message($message);
     # if($this->email->send())
     #{
     # echo 'Email sent.';
    # }
   #  else
   # {
    # show_error($this->email->print_debugger());
   # }




       // move_uploaded_file($_FILES['path_of_file']['tmp_name'], "pic/$fileName");
       
      
            
        
       
    
    
    /*
     * function to update company
     */
    function update_company($company_id,$params)
    {
        $this->db->where('company_id',$company_id);
        return $this->db->update('company',$params);
    }
    
    /*
     * function to delete company
     */
    function delete_company($company_id)
    {
        return $this->db->delete('company',array('company_id'=>$company_id));
    }
}
