<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_product_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get company_product by company_product_id
     */
    function get_company_product($company_product_id)
    {
        return $this->db->get_where('company_product',array('company_product_id'=>$company_product_id))->row_array();
    }
        
    /*
     * Get all company_product
     */
    function get_all_company_product()
    {
        $this->db->order_by('company_product_id', 'desc');
        return $this->db->get('company_product')->result_array();
    }
        
    /*
     * function to add new company_product
     */
    function add_company_product($params)
    {
        $this->db->insert('company_product',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update company_product
     */
    function update_company_product($company_product_id,$params)
    {
        $this->db->where('company_product_id',$company_product_id);
        return $this->db->update('company_product',$params);
    }
    
    /*
     * function to delete company_product
     */
    function delete_company_product($company_product_id)
    {
        return $this->db->delete('company_product',array('company_product_id'=>$company_product_id));
    }
}
