<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard_model extends CI_Model{
    function __construct()
    {
        parent::__construct();
        
    }
    
    /*
     * Get dashboard_info by bri_id
     */
    function get_company($id)
    {
        return $this->db->get_where('company',array('id'=>$id))->row_array();
      
  
    }
    

    function get_all_programmes()
    {
        $this->db->order_by('programme_id', 'desc');
        return $this->db->get('programmes')->result_array();
    }

    function get_all_company()
    {
       // $this->db->order_by('id', 'desc');
        return $this->db->get('company')->result_array();
    }
        
}
