<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Person_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get person by person_id
     */
    function get_person($person_id)
    {
        return $this->db->get_where('person',array('person_id'=>$person_id))->row_array();
    }
        
    /*
     * Get all person
     */
    function get_all_person()
    {
        $this->db->order_by('person_id', 'desc');
        return $this->db->get('person')->result_array();
    }
        
    /*
     * function to add new person
     */
    function add_person($params)
    {
        $this->db->insert('person',$params);
        $this->db->insert('company_person',array_slice($params, 13)); 
        
        return $this->db->insert_id();
        //$this->db->query('select company_id, company_name from company');
       
    }
    
    /*
     * function to update person
     */
    function update_person($person_id,$params)
    {
        $this->db->where('person_id',$person_id);
        return $this->db->update('person',$params);
    }
    
    /*
     * function to delete person
     */
    function delete_person($person_id)
    {
        return $this->db->delete('person',array('person_id'=>$person_id));
    }


    public function get_associatedCompany() { 
        $result = $this -> db -> select('company_id, company_name') -> get('company') -> result_array(); 
 
        $person_company = array(); 
        foreach($result as $r) { 
            $person_company[$r['company_id']] = $r['company_name']; 
        } 
        $person_company['#'] = 'Not in list'; 
        
        $person_company[''] = 'Select Associated Company...'; 
        
        return $person_company; 
    } 
}
