<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programmes_and_company_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get programmes_and_company by programmes_id
     */
    function get_programmes_and_company($programmes_id)
    {
        return $this->db->get_where('programmes_and_companies',array('programmes_id'=>$programmes_id))->row_array();
    }
        
    /*
     * Get all programmes_and_companies
     */
    function get_all_programmes_and_companies()
    {
        $this->db->order_by('programmes_id', 'desc');
        return $this->db->get('programmes_and_companies')->result_array();
    }
        
    /*
     * function to add new programmes_and_company
     */
    function add_programmes_and_company($params)
    {
        $this->db->insert('programmes_and_companies',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update programmes_and_company
     */
    function update_programmes_and_company($programmes_id,$params)
    {
        $this->db->where('programmes_id',$programmes_id);
        return $this->db->update('programmes_and_companies',$params);
    }
    
    /*
     * function to delete programmes_and_company
     */
    function delete_programmes_and_company($programmes_id)
    {
        return $this->db->delete('programmes_and_companies',array('programmes_id'=>$programmes_id));
    }
}
