<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Programme_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get programme by programme_id
     */
    function get_programme($programme_id)
    {
        return $this->db->get_where('programmes',array('programme_id'=>$programme_id))->row_array();
    }
        
    /*
     * Get all programmes
     */
    function get_all_programmes()
    {
        $this->db->order_by('programme_id', 'desc');
        return $this->db->get('programmes')->result_array();
    }
        
    /*
     * function to add new programme
     */
    function add_programme($params)
    {
        $this->db->insert('programmes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update programme
     */
    function update_programme($programme_id,$params)
    {
        $this->db->where('programme_id',$programme_id);
        return $this->db->update('programmes',$params);
    }
    
    /*
     * function to delete programme
     */
    function delete_programme($programme_id)
    {
        return $this->db->delete('programmes',array('programme_id'=>$programme_id));
    }
}
